version: '3.8'
services:
  go-project:
    build:
      context: .
      dockerfile: Dockerfile
    image: ops-cy-245:9998/library/go-project:${BUILD_ID}
    ports:
      - "8070:8080"
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - DATABASE_TYPE=mysql
      - DATABASE_USER=cy
      - DATABASE_PASSWORD=12345
      - DATABASE_HOST=172.16.10.11
      - DATABASE_NAME=cloud
      - REDIS_HOST=172.16.10.12
      - REDIS_INDEX=1
    networks: 
      app_net:  # 调用下面 networks 定义的 app_net 网络
        ipv4_address: 172.16.10.13
  
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cloud
      MYSQL_USER: cy
      MYSQL_PASSWORD: 12345
    networks: 
      app_net:  # 调用下面 networks 定义的 app_net 网络
        ipv4_address: 172.16.10.11
      
  redis:
    image: redis:7.2.5-alpine
    networks: 
      app_net:  # 调用下面 networks 定义的 app_net 网络
        ipv4_address: 172.16.10.12
    
    
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet: 172.16.10.0/24