version: '3.8'
services:
  go-project:
    build:
      context: .
      dockerfile: Dockerfile
    image: ops-cy-245:9998/library/go-project:${BUILD_ID}
    ports:
      - "8070:8080"
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=12345
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks: 
      app_net:  # 调用下面 networks 定义的 app_net 网络
        ipv4_address: 172.16.238.10
  
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cloud
      MYSQL_USER: cy
      MYSQL_PASSWORD: 12345
    networks: 
      app_net:  # 调用下面 networks 定义的 app_net 网络
        ipv4_address: 172.16.238.11
      
  redis:
    image: redis:7.2.5-alpine
    networks: 
      app_net:  # 调用下面 networks 定义的 app_net 网络
        ipv4_address: 172.16.238.12
    
    
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet: 172.16.10.0/24